# Generated by Django 5.2.1 on 2026-05-15 18:11

import apps.recruitment.utils.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('cv_file', models.FileField(upload_to='cvs/', validators=[apps.recruitment.utils.validators.validate_cv_file])),
                ('extracted_text', models.TextField(blank=True)),
                ('years_of_experience', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('skills', models.JSONField(blank=True, default=list)),
                ('education', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['full_name', 'email'], name='recruitment_full_na_3f3c0b_idx'), models.Index(fields=['uploaded_at'], name='recruitment_uploade_34901d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], db_index=True, default='full_time', max_length=30)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('minimum_experience', models.PositiveSmallIntegerField(default=0)),
                ('education_requirement', models.CharField(blank=True, max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title', 'company_name'], name='recruitment_title_adf58c_idx'), models.Index(fields=['employment_type', 'created_at'], name='recruitment_employm_ee516d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommendation_status', models.CharField(choices=[('shortlisted', 'Shortlisted'), ('consider', 'Consider'), ('rejected', 'Rejected')], db_index=True, default='consider', max_length=20)),
                ('generated_interview_questions', models.JSONField(blank=True, default=list)),
                ('analysis_created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='recruitment.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='recruitment.job')),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
                'ordering': ['-match_score', '-analysis_created_at'],
                'indexes': [models.Index(fields=['job', 'match_score'], name='recruitment_job_id_29e6a9_idx'), models.Index(fields=['candidate', 'match_score'], name='recruitment_candida_775459_idx'), models.Index(fields=['recommendation_status', 'match_score'], name='recruitment_recomme_b7a312_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'candidate'), name='unique_analysis_per_job_candidate')],
            },
        ),
    ]
