# Generated by Django 5.2.1 on 2026-05-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_candidate_extracted_at_candidate_extraction_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='analysis_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='analyzed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['analysis_completed', 'analyzed_at'], name='recruitment_analysi_14e0b7_idx'),
        ),
    ]
